# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
 - name: SpacyNLP
   model: "en_core_web_lg"
   case_sensitive: False
 - name: SpacyTokenizer
 - name: SpacyFeaturizer
 - name: CRFEntityExtractor
 - name: SklearnIntentClassifier
   C: [1,2,5,10,20,100]
   kernels: ["linear","poly","rbf"]
   "gamma": [0.01, 0.05, 0.1, 0.5]
   "max_cross_validation_folds": 8
   "scoring_function": "f1_weighted"
 - name: ResponseSelector
   epochs: 100
   model_confidence: "linear_norm"
   constrain_similarities: true
 - name: FallbackClassifier
   threshold: 0.3

# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 6
    epochs: 100
  - name: RulePolicy
